include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
#    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_left_central
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
#    snippet: studio-rpc-usb-uart
    artifact-name: torabo_tsuki_lp_right_peripheral
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
#    snippet: studio-rpc-usb-uart
    artifact-name: torabo_tsuki_lp_left_peripheral
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
#    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_lp_right_central
    snippets:
      - studio-rpc-usb-uart
      - zmk-usb-logging
  - board: bmp_boost
    shield: settings_reset
