name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
    with:
      config: |
        include:
          - board: nice_nano_v2
            shield: corne_left
            snippet: zmk-usb-logging
